### ISSUE TITLE
pre-commit ruins requirements.txt encoding

### ISSUE THREAD

**Issue by 0riginaln0** [quality-software-development/lazy-lecture#16]
pre-commit форматирует requirements.txt так, что pip install -r requirements.txt падает с ошибкой
```
UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x0a in position 650: truncated data
```  

Чтобы pip всё-таки смог скачать зависимости, пришлось убирать поломанный newline 

![image](https://github.com/user-attachments/assets/5f2d038d-39ab-4d8a-91a9-7554c6f18c7a)

**Comment by Quakumei** [comment]
У меня почему-то твой requirements.txt как binary файл на гитхабе отображается обычно, с ним все хорошо?

**Comment by Quakumei** [comment]
![image](https://github.com/user-attachments/assets/a315aff3-a0ab-48f2-ab23-414a84cd0e79)

**Comment by Quakumei** [comment]
Может у тебя файл почему-то в utf-16? На линуксе можно проверить с помощью `file requirements.txt`

**Comment by 0riginaln0** [comment]
> Может у тебя файл почему-то в utf-16? На линуксе можно проверить с помощью `file requirements.txt`

да, в utf-16

```sh
$ file bot/requirements.txt 
bot/requirements.txt: Unicode text, UTF-16, little-endian text, with CRLF line terminators
```

**Comment by 0riginaln0** [comment]
![image](https://github.com/user-attachments/assets/baf281c8-87f2-497c-a951-d991908ac15b)

хз почему в diff не отображается. Если просто в ветку зайти, то всё видно

**Comment by 0riginaln0** [comment]
сохраню в utf-8, запушу

**Comment by 0riginaln0** [comment]
С utf-8 прошло проверку. Окей, этот ишью можно закрывать
